INSERT INTO warehouse(name, capacity, street, city, state, zip) VALUES ('AZ Warehouse', 300, '123 First Street', 'Phoenix', 'Arizona', 83543);

INSERT INTO product_type(name) VALUES ('Outdoors');

INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventurePro Hiking Backpack', 1, 'The AdventurePro Hiking Backpack is designed for the avid adventurer. It features a durable waterproof construction, multiple compartments for organizing gear, and a comfortable ergonomic design. Get ready to conquer the great outdoors with this backpack!', 89.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrailBlazer Camping Tent', 1, 'The TrailBlazer Camping Tent is your ultimate companion for outdoor camping trips. It offers easy setup, spacious interior, and weather-resistant materials. Stay protected from the elements and enjoy a comfortable camping experience with this tent.', 149.99, 5);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrekMaster Sleeping Bag', 1, 'The TrekMaster Sleeping Bag is perfect for a good night''s sleep under the stars. It''s made with high-quality insulation, providing warmth and comfort in various weather conditions. Sleep soundly on your outdoor adventures with this sleeping bag.', 79.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventureLite Portable Hammock', 1, 'The AdventureLite Portable Hammock is your ticket to relaxation in the wilderness. It''s lightweight, easy to set up, and made of durable materials. Unwind and enjoy a peaceful moment wherever you go with this hammock.', 49.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('ProTrek Trekking Poles', 1, 'ProTrek Trekking Poles are designed for stability and support on rugged terrains. These adjustable poles provide balance, reduce strain on joints, and enhance your hiking experience. Conquer challenging trails with these reliable trekking poles.', 39.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('SummitGuard Waterproof Jacket', 1, 'The SummitGuard Waterproof Jacket is a must-have for outdoor enthusiasts. It offers excellent protection against rain and wind while remaining breathable. Stay dry and comfortable in any weather with this reliable jacket.', 129.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('SolarTrail Portable Charger', 1, 'The SolarTrail Portable Charger is your power source on the go. Harness the sun''s energy to charge your devices while exploring the outdoors. With its compact design and multiple charging ports, you''ll never run out of battery again.', 59.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventureSeeker Binoculars', 1, 'AdventureSeeker Binoculars bring the world closer to you. With high-quality lenses and a durable build, these binoculars provide clear and crisp views of wildlife, landscapes, and more. Enhance your outdoor observation with these binoculars.', 69.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrailTracker GPS Watch', 1, 'The TrailTracker GPS Watch is your reliable navigation companion. It tracks your routes, distance, speed, and more, ensuring you never get lost in the wilderness. Stay on track and explore confidently with this GPS watch.', 199.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('BaseCamp Portable Grill', 1, 'The BaseCamp Portable Grill is perfect for outdoor cooking adventures. It features a large cooking surface, adjustable heat settings, and a compact design for easy transportation. Enjoy delicious grilled meals wherever your adventure takes you.', 149.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventureGlow LED Lantern', 1, 'The AdventureGlow LED Lantern illuminates your camping nights. With adjustable brightness and a long battery life, this lantern provides reliable lighting in the great outdoors. Light up your surroundings and create a cozy ambiance with this lantern.', 29.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AlpineClimb Climbing Harness', 1, 'The AlpineClimb Climbing Harness is engineered for safety and comfort during rock climbing and mountaineering. It features adjustable straps, padded waistbelt, and sturdy attachment points. Climb with confidence and security using this climbing harness.', 89.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('ExplorerPro Camping Cookware Set', 1, 'The ExplorerPro Camping Cookware Set equips you with everything you need for outdoor cooking. This compact and lightweight set includes pots, pans, utensils, and a portable stove. Prepare delicious meals in the wilderness with this cookware set.', 59.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrailRider Bike Helmet', 1, 'The TrailRider Bike Helmet combines style, comfort, and safety for cycling enthusiasts. It features a lightweight design, adjustable fit, and excellent ventilation. Ride with confidence and protection with this bike helmet.', 49.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventurePro Waterproof Dry Bag', 1, 'The AdventurePro Waterproof Dry Bag keeps your gear safe and dry on water-based adventures. It''s made with durable materials, features a roll-top closure, and comes in various sizes. Protect your belongings from water damage with this reliable dry bag.', 34.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrekTrax Portable Bluetooth Speaker', 1, 'The TrekTrax Portable Bluetooth Speaker provides a soundtrack for your outdoor escapades. It''s compact, water-resistant, and delivers high-quality sound. Enjoy your favorite music wherever you go with this portable speaker.', 79.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('SummitView Camping Chair', 1, 'The SummitView Camping Chair offers comfort and convenience while relaxing outdoors. It features a sturdy frame, adjustable recline, and a built-in cooler pouch. Sit back, relax, and enjoy the views with this comfortable camping chair.', 49.99, 3);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('AdventureCapture Action Camera', 1, 'The AdventureCapture Action Camera captures your thrilling moments in high definition. It''s waterproof, shockproof, and comes with various mounting options. Record your outdoor adventures with stunning clarity using this action camera.', 119.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('TrailBlazer Portable Water Filter', 1, 'The TrailBlazer Portable Water Filter ensures clean and safe drinking water on your outdoor expeditions. It removes bacteria and protozoa, making water from natural sources safe to consume. Stay hydrated and healthy with this portable water filter.', 79.99, 1);
INSERT INTO product(name, product_type_id, description, price, size) VALUES ('SummitPro Insulated Cooler', 1, 'The SummitPro Insulated Cooler keeps your food and drinks cool for extended outdoor trips. It features a durable construction, ample storage space, and insulation to maintain temperature. Keep your refreshments chilled and ready with this reliable cooler.', 99.99, 3);

INSERT INTO item(product_id, warehouse_id) VALUES (1, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (2, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (3, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (4, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (5, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (6, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (7, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (8, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (9, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (10, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (11, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (12, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (13, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (14, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (15, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (16, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (17, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (18, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (20, 1);
INSERT INTO item(product_id, warehouse_id) VALUES (20, 1);